title: Drake Watson
logo: "/assets/img/circle-headshot.png?raw=true"
description:

  <p align="center">
  <a href="mailto:watsond1@uci.edu">Email</a> |
  <a href="https://www.linkedin.com/in/drake-watson-733a8a20b/">LinkedIn</a> |
  <a href="https://github.com/datadraco">GitHub</a> |
    <a href="pdf/Academic-Resume.pdf">Resume</a>
  </p>

  I am currently a Statistical Research Programmer at Chapman University and Masters in Data Science student at the Donald Bren School of Information and Computer Science at the University of California - Irvine.
  <br><br>
  I have a BA in Mathematics from the University of Washington. I have a passion for analysis and visualizations as tools for driving positive change and answering complex questions.
  <br><br>


theme: jekyll-theme-minimal
